[package]
name = "ibr"
version = "0.1.0"
authors = ["Heribert Innoq"]

[dependencies]
gotham = "0.2.1"
hyper = "0.11"
mime = "0.3.5"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
crypto-hash = "0.3.1"
rayon = "0.9.0"
